---
title: "Machine_LEarning"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
iris <- read.csv(url("http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"), 
                 header = FALSE)

names(iris) <- c("Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width", "Species")

iris
```

```{r}
library(ggvis)

iris %>% 
  ggvis(~Sepal.Length, ~Sepal.Width, fill = ~Species) %>% 
  layer_points()

iris %>% 
  ggvis(~Petal.Length, ~Petal.Width, fill = ~Species) %>% 
  layer_points()
```

```{r}
table(iris$Species) 

round(prop.table(table(iris$Species)) *100, digits = 1)


```

```{r}
cor(iris$Petal.Length, iris$Petal.Width)



x=levels(iris$Species)

iris$species


cor(iris[iris$Species==x[1], 1:4])
```

```{r}
summary(iris) 

summary(iris[c("Petal.Width", "Sepal.Width")])
```

```{r}
library(class)

normalize <- function(x) {
num <- x - min(x)
denom <- max(x) - min(x)
return (num/denom)
}

iris_norm <- as.data.frame(lapply(iris[1:4], normalize))

summary(iris_norm)
```

```{r}
set.seed(1234)

ind <- sample(2, nrow(iris), replace = TRUE, prob = c(0.67, 0.33))
ind
```

```{r}
iris.training <- iris[ind==1, 1:4]

head(iris.training)

iris.test <- iris[ind==2, 1:4]

head(iris.test)
```

```{r}
# Compose `iris` training labels
iris.trainLabels <- iris[ind==1,5]

# Inspect result
print(iris.trainLabels)

# Compose `iris` test labels
iris.testLabels <- iris[ind==2, 5]

# Inspect result
print(iris.testLabels)

```

```{r}
iris_pred <- knn(train = iris.training, test = iris.test, cl = iris.trainLabels, k=3)

# Inspect `iris_pred`
iris_pred

```

```{r}
# Put `iris.testLabels` in a data frame
irisTestLabels <- data.frame(iris.testLabels)

# Merge `iris_pred` and `iris.testLabels` 
merge <- data.frame(iris_pred, iris.testLabels)

# Specify column names for `merge`
names(merge) <- c("Predicted Species", "Observed Species")

# Inspect `merge` 
merge
```

```{r}
library(gmodels)

CrossTable(x = iris.testLabels, y = iris_pred, prop.chisq=FALSE)
```
