---
title: "MLB Analytics"
output:
  pdf_document:
    toc: yes
  html_document:
    date: 3/22/2022
    theme: journal
    toc: yes
    toc_float: yes
    code_folding: hide
---

Drew Weber

### --------------------------------------------------

```{css, echo = FALSE}

table, td, th {
  border: none;
  padding-left: 1em;
  padding-right: 1em;
  margin-left: auto;
  margin-right: auto;
  margin-top: 1em;
  margin-bottom: 1em;
}

```

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE, echo=FALSE}
library(tidyverse)
library(nflscrapR)
library(devtools)
library(dplyr)
library(nflfastR)
library(stargazer)
library(ggplot2)
library(shiny)
library(na.tools)
library(ggimage)
library(nflreadr)
library(ggrepel)
library(scales)
```

```{r, echo=FALSE, include=FALSE}
MLB_2021_analytics <- read.csv("/Users/drew/Downloads/MLB_2021_Analytics.csv")
```

```{r, message=FALSE, include=FALSE}
MLB_2021_analytics <- MLB_2021_analytics %>%
  group_by(player_id, last_name) 
```

```{r, include=FALSE, message=FALSE, warning=FALSE}
OPS_reg <-lm(home_run~  launch_angle_avg + exit_velocity_avg + sweet_spot_percent + barrel_batted_rate, data = MLB_2021_analytics)

```

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
stargazer(OPS_reg,
          type="text",
          title = "OPS",
          style = "aer",
          covariate.labels = c("Launch Angle", "Exit Velo", "Sweet Spot%", "Barrel Batted%"))
          
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
MLB_2021_analytics %>%
  ggplot(aes(x = launch_angle_avg, y = home_run)) +

  geom_hline(yintercept = mean(MLB_2021_analytics$home_run), color = "red", linetype = "dashed", alpha=0.5) +

  geom_vline(xintercept =  mean(MLB_2021_analytics$launch_angle_avg), color = "red", linetype = "dashed", alpha=0.5) +

  geom_point(color = "red", cex=MLB_2021_analytics$total_pa / 300, alpha = .75) +

  geom_text_repel(aes(label=last_name), size = 2) +

  stat_smooth(geom='line', alpha=0.5, se=FALSE, method='lm')+

  labs(x = "Launch Angle",
       y = "Homers",
       title = "Launch Angles",
       caption = "Min. 150 PA") +

  theme_bw() +
 
  theme(
    plot.title = element_text(size = 12, hjust = 0.5, face = "bold")
  ) +
 
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10))

```

