---
title: MLB Analytics
author: Drew J. Weber
date: '2022-03-22'
slug: mlb-attempt-85
categories: []
tags: []
---

### 

```{css, echo = FALSE}

table, td, th {
  border: none;
  padding-left: 1em;
  padding-right: 1em;
  margin-left: auto;
  margin-right: auto;
  margin-top: 1em;
  margin-bottom: 1em;
}

```

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE, echo=FALSE}
library(tidyverse)
library(devtools)
library(dplyr)
library(stargazer)
library(ggplot2)
library(shiny)
library(na.tools)
library(ggimage)
library(ggrepel)
library(scales)
library(pacman)
library(Lahman)
library(pitchRx)
```




```{r}
team_consistency(2015)
```


```{R}
bref_daily_batter <- bref_daily_batter("2021-01-11", "2021-12-11")

statcast_2021 <- scrape_statcast_savant("2021-01-11", "2021-12-11")

baseball_2021 <- bref_daily_batter("2021-01-11", "2021-12-11") %>%
  dplyr::filter(PA > 200) %>%
  woba_plus %>%
  dplyr::arrange(desc(wOBA)) %>%
  dplyr::select(Name, Team, season, PA, wOBA, wOBA_CON) %>%
  dplyr::glimpse()
```



```{r, echo=FALSE, include=FALSE}
MLB_2021_analytics <- read.csv("/Users/drew/Downloads/MLB_2021_Analytics.csv")
```

```{r, message=FALSE, include=FALSE}
MLB_2021_analytics <- MLB_2021_analytics %>%
  group_by(player_id, last_name) 

#Removed b_ from column names
  # for col in 1 to number of columns in df {
     #colnames(df)[] <- sub("b_", "with a blank spot", colnames(MLB_2021_analytics)[col])
#NOTE: If there is a * after B_, it will remove all Bs and underscored in all the colnames. We do not want this.
for ( col in 1:ncol(MLB_2021_analytics)){
    colnames(MLB_2021_analytics)[col] <-  sub("b_", "", colnames(MLB_2021_analytics)[col])
}
```



## 1. Home Run
```{r, include=FALSE, message=FALSE, warning=FALSE}
HR_reg <-lm(home_run~  launch_angle_avg + exit_velocity_avg + sweet_spot_percent + barrel_batted_rate, data = MLB_2021_analytics)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
stargazer(HR_reg,
          type="html",
          title = "How to hit Home Runs",
          style = "aer",
          covariate.labels = c("Launch Angle", "Exit Velo", "Sweet Spot%", "Barrel Batted%"))
          
```

## 2. Strikeout

```{r, include=FALSE, message=FALSE, warning=FALSE}
k_reg <-lm(strikeout~  oz_swing_percent + z_swing_miss_percent + called_strike  + launch_angle_avg, data = MLB_2021_analytics)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
stargazer(k_reg,
          type="html",
          title = "Strikeouts",
          style = "aer",
          covariate.labels = c("Out of Zone Swing%", "In Zone Swing and Miss%", "Called Strikes", "Launch Angle Average"))
          
```

## 3. Density Graph
```{r, include=FALSE, echo=FALSE}
MLB_2021_analytics <- MLB_2021_analytics %>% 
  filter(total_pa > 200, on_base_percent > .299) %>%
  summarize(total_pa,
            isolated_power,
            slg_percent,
            home_run,
            on_base_percent,
            xobp,
            xiso,
            xslg,
            last_name)
```

```{r}

Power_Hitting <- MLB_2021_analytics %>% 
  filter(total_pa > 200, on_base_percent > .299) %>%
  summarize(total_pa,
            isolated_power,
            slg_percent,
            home_run,
            on_base_percent,
            xobp,
            xiso,
            xslg,
            last_name)
```
  

```{r, echo=FALSE, message=FALSE, warning=FALSE}
Power_Hitting %>%
  ggplot(aes(x = isolated_power, y = slg_percent)) +

  geom_hline(yintercept = mean(Power_Hitting$slg_percent), color = "red", linetype = "dashed", alpha=0.5) +

  geom_vline(xintercept =  mean(Power_Hitting$isolated_power), color = "red", linetype = "dashed", alpha=0.5) +
  
  geom_point(color = "red", cex=Power_Hitting$home_run /10, alpha = .6) +

  geom_text_repel(aes(label=last_name), size = 2.75 ) +

  stat_smooth(geom='line', alpha=0.5, se=FALSE, method='lm')+
  
  labs(x = "ISO",
       y = "Slugging",
       title = "ISO vs. Slugging",
       caption = "Min. 200 PA") +
 
  theme_bw() +

  theme(
    plot.title = element_text(size = 14, hjust = 0.5, face = "bold")
  ) 


Power_Hitting %>%
  ggplot(aes(x = xobp, y = on_base_percent)) +

  geom_hline(yintercept = mean(Power_Hitting$on_base_percent), color = "red", linetype = "dashed", alpha=0.5) +

  geom_vline(xintercept =  mean(Power_Hitting$xobp), color = "red", linetype = "dashed", alpha=0.5) +
  
  geom_point(color = "red", cex=Power_Hitting$home_run /10, alpha = .6) +

  geom_text_repel(aes(label=last_name), size = 2.75 ) +

  stat_smooth(geom='line', alpha=0.5, se=FALSE, method='lm')+
  
  labs(x = "xOBP",
       y = "OBP",
       title = "xOBP vs. OBP",
       caption = "Min. 200 PA") +
 
  theme_bw() +

  theme(
    plot.title = element_text(size = 14, hjust = 0.5, face = "bold")
  ) 

```

Slow players like Mike Zunino have some of the highest ISO's in the league, but his slugging falls behind.  How much does speed have to do with getting extra bases?

```{r, include=FALSE, message=FALSE, warning=FALSE}
iso_reg <-lm(slg_percent~  sprint_speed + isolated_power, data = MLB_2021_analytics)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
stargazer(iso_reg,
          type="html",
          title = "Slugging",
          style = "aer",
          covariate.labels = c("Sprint Speed", "ISO"))
          
```


